(library
 (name riscv32im_stylus)
 (public_name riscv32im_stylus)
 (libraries
  ppx_deriving
  ppx_deriving.std
  ppx_deriving.eq
  ppx_deriving.show
  ppx_sexp_conv
  libbinutils)
 (inline_tests)
 (preprocess
  (pps
   ppx_inline_test
   ppx_deriving.show
   ppx_deriving.eq
   ppx_deriving.make
   ppx_deriving.std
   ppx_sexp_conv)))
