(library
 (name libbinutils)
 (public_name libbinutils)
 (virtual_deps conf-binutils)
 (flags (:standard -w -9-27))
 (c_library_flags :standard -lbfd)
 (libraries unix)
 (ctypes
  (external_library_name libbfd)
  (build_flags_resolver vendored)
  (headers (include "bfd.h"))
  (type_description
   (instance Types)
   (functor Type_description))
  (function_description
   (concurrency unlocked)
   (instance Functions)
   (functor Function_description))
  (generated_types Types_generated)
  (generated_entry_point Generated)))
